flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- StateVar-1.1.0.3
- adjunctions-4.3
- ansi-terminal-0.6.2.3
- base-orphans-0.5.0
- bifunctors-5.2
- comonad-5
- contravariant-1.4
- distributive-0.5.0.2
- exceptions-0.8.2.1
- free-4.12.4
- hashable-1.2.4.0
- kan-extensions-5.0.1
- lens-4.13.1
- monadLib-3.7.3
- mtl-2.2.1
- parallel-3.2.1.0
- prelude-extras-0.4.0.3
- pretty-1.1.3.2
- primitive-0.6.1.0
- profunctors-5.2
- reflection-2.1.1.1
- semigroupoids-5.0.1
- semigroups-0.18.0.1
- stm-2.4.4.1
- tagged-0.8.2
- template-haskell-2.10.0.0
- terminal-size-0.3.2.1
- text-1.2.2.0
- transformers-compat-0.5.1.4
- unordered-containers-0.2.6.0
- vector-0.11.0.0
- void-0.7.1
resolver: ghc-7.10.2
